[project]
name = "tast-new"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "coloredlogs>=15.0.1",
    "fastapi[all]>=0.116.1",
    "psycopg2>=2.9.10",
]
